Add upload preview
WING-NUS/SSID pull request #183
Opened 2022-07-11 08:54 UTC by sibinhho99

([#32](`https://github.com/WING-NUS/SSID/issues/32`))
![Screenshot 2022-07-11 at 4 43 50 PM](https://user-images.githubusercontent.com/29513997/178225858-af74a44d-140f-47db-896e-fd309d5e158d.png)
![Screenshot 2022-07-11 at 4 43 39 PM](https://user-images.githubusercontent.com/29513997/178225872-cdb11ff7-3de2-40e1-b736-7361eb7ffbfc.png)
![Screenshot 2022-07-11 at 4 44 00 PM](https://user-images.githubusercontent.com/29513997/178225892-e559044b-7e26-4c8c-b5d6-f84408c0e64a.png)

2022-07-11 09:12 UTC, knmnyn commented on app/views/assignments/_form.html.erb
> -  <p> Hover over ⓘ for more details about any terminology.</p>
Not sure why diff generates this block as a difference in code.  It looks identical.

2022-07-11 09:19 UTC, knmnyn reviewed
Generally looks ok, but still needs work on documentation.

2022-07-11 09:19 UTC, knmnyn commented on app/views/assignments/_form.html.erb
> +<%= javascript_include_tag "jszip.min" %>
You should document somewhere in README.md that the jszip.min comes from where.

2022-07-11 09:19 UTC, knmnyn commented on app/views/assignments/_form.html.erb
> +<%= javascript_include_tag "jszip.min" %>
And its MD5 hash so that the source has a known version.

2022-07-27 07:06 UTC, nguyen-mai-huong commented
1. It's a good idea to organize code in a cleaner way. Just that we need to be a bit careful when doing it.
Currently, assignments_file_upload is globally accessible. These functions should be available to Assignment only.

2. Another note is that it's good to organize jszip.min.js into a library folder like /javascripts/jit or /javascripts/prettify.
It will help us keep track of the external JS libs we are using, and let us know when we need to upgrade JS dependencies management when the number of libs grows.

2022-07-27 07:18 UTC, nguyen-mai-huong requested changes

2022-07-27 07:18 UTC, nguyen-mai-huong commented on app/assets/javascripts/assignments_file_upload.js
> +checkbox.onchange = function () {
The 3-dot menu site-wide is not working e.g. cannot access Edit/Delete a course ...

2022-07-27 07:18 UTC, nguyen-mai-huong commented on app/assets/javascripts/assignments_file_upload.js
> +$("#assignment_file").attr("onchange", "onAssignmentFileInputChange(this)");
Not recommended way of binding an event. You can try
`        $("#assignment_file").on("change", function() {
          Assignment.changeAssignmentFileInput(this);
        });`

2022-07-27 09:48 UTC, knmnyn commented on app/views/assignments/_form.html.erb
> +<%= javascript_include_tag "jszip.min" %>
Yes, that is sufficient.  There should be documentation in the README.md or subcomponent README that documents such dependencies, much like what a Gemfile does.

2022-08-01 04:07 UTC, merged