Add showing product update message
WING-NUS/SSID pull request #249
Opened 2022-12-16 06:52 UTC by sibinhho99

## Description

Allows maintainer to make product update announcements

## Related Issue

[https://github.com/WING-NUS/SSID/issues/247](https://github.com/WING-NUS/SSID/issues/247)

## Motivation and Context

Prof @knmnyn's request

## How Has This Been Tested?

Local testing

## Screenshots (if appropriate):
Demo: [https://youtu.be/DtyGSvB5m-U](https://youtu.be/DtyGSvB5m-U)

![Screenshot 2022-12-16 at 2 48 48 PM](https://user-images.githubusercontent.com/29513997/208039798-c23b8df5-b98e-45e6-a979-8255b3946a6b.png)

The admin can set new messages or toggle the visibility of the message on/off using rake tasks

![Screenshot 2022-12-16 at 2 48 18 PM](https://user-images.githubusercontent.com/29513997/208039850-559e139d-5496-4b28-9d67-6f38976dde90.png)
<img width="685" alt="image" src="https://github.com/WING-NUS/SSID/assets/29513997/a2b427ed-d3e7-48d8-a8f6-59ccdf68c2ab">

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

Closes [247](https://github.com/WING-NUS/SSID/issues/247).

2023-09-13 17:08 UTC, huyuxin0429 commented
Hmm does the message just stay there? How do we remove the message once we are done announcing?

2023-09-13 17:29 UTC, knmnyn commented
Are you using Rails' flash message system?  I think that feature is designed for exactly such purposes?

2023-09-16 08:06 UTC, huyuxin0429 commented
> > Hmm does the message just stay there? How do we remove the message once we are done announcing?
> 
> Currently the message just stay there. I can add the function for maintainer to turn it on/ off
> 
> > Are you using Rails' flash message system? I think that feature is designed for exactly such purposes?
> 
> Yes I am using Rails' flash message

Yeah adding a functionality to turn it on and off will be great! Please document the instructions you have provided in maybe an admin user guide.

2023-09-16 08:07 UTC, huyuxin0429 requested changes
Please add ability to turn the banner on/off and document steps in admin usage guide.

2024-01-13 11:10 UTC, merged