Add anonymiser script to anonymise sensitive data in students' code in the test files
WING-NUS/SSID pull request #50
Opened 2020-11-23 18:29 UTC by Riyas97

2020-11-24 03:18 UTC, knmnyn requested changes
Needs work.  

* Needs function and file level documentation.
* Needs an example input and output case.
* Needs a unit test harness to run the example input to verify that an installation achieves the required output.

2020-11-24 03:18 UTC, knmnyn commented on Anonymiser.py
> +    path = [Insert path of folder where the test files are stored]
Set a default path and use a better variable name (`default_path`).

2020-11-24 03:18 UTC, knmnyn commented on Anonymiser.py
> +
This is your library of regex for anonymisation.  You need to mark it more clearly.  Is there any other logic that you are using for this?  If not make that clear that this is the whole thing.  What is the order of precedence in the processing?

2021-06-17 06:58 UTC, Riyas97 commented
Will create a new PR due to new changes and requirements. As such, closing this PR.

2021-06-17 06:58 UTC, closed without merging