Update submission_clusters.js.coffee and show.json.erb to display per…
WING-NUS/SSID pull request #89
Opened 2021-07-20 12:12 UTC by nguyen-mai-huong

adding similarity percentages to Similarity Cluster graphs

2021-07-21 03:47 UTC, knmnyn approved these changes

2021-07-21 03:47 UTC, knmnyn commented on app/assets/javascripts/submission_clusters.js.coffee
> +          $("#canvas_wrapper_"+clusterId+"-label").append("<div class=\"edgeLabel\" style=\""+style+"\"><a href=\""+adj.data.submissionSimilarityUrl+"\" style=\"margin-right: 10px\">view</a><span>\""
UI string could be better, but ok.

2021-07-21 03:49 UTC, knmnyn commented
PR could be more detailed to add in a screenshot of the (intended) outcome.

2021-07-21 16:05 UTC, Riyas97 requested changes
Code LGTM. But, I just have a small request. Can you post a pic about how the UI would look like? In the past, when I was working on similar issues, I had to change the css file. So, I just wanted to check whether such changes would be necessary here. Thanks a lot.

2021-07-22 10:03 UTC, nguyen-mai-huong commented
> Code LGTM. But, I just have a small request. Can you post a pic about how the UI would look like? In the past, when I was working on similar issues, I had to change the css file. So, I just wanted to check whether such changes would be necessary here. Thanks a lot.

Hi Riyas, attached is how UI looks like.

![graph-with-percentage](https://user-images.githubusercontent.com/5399322/126622424-2d6e39da-2caf-486a-bc23-6f15e991774c.png)

2021-07-28 04:56 UTC, Riyas97 approved these changes

2021-07-28 04:57 UTC, merged

2021-07-28 04:57 UTC, Riyas97 commented
Thanks.